# Generated by Django 5.2.10 on 2026-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('attack_count', models.IntegerField()),
                ('threshold', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('attack_type', models.CharField(max_length=50)),
                ('src_ip', models.CharField(max_length=45)),
                ('dst_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('raw_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attack_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('threshold_value', models.IntegerField()),
                ('time_window', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'threshold_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_ip', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=255)),
                ('attack_count', models.IntegerField(default=0)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='pending', max_length=20)),
                ('security_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip_block',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
