# Generated by Django 5.2.10 on 2026-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('instance_id', models.CharField(max_length=50)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('security_group_id', models.CharField(max_length=50)),
                ('security_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region_id', models.CharField(default='ap-southeast-3', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instance_mapping',
                'ordering': ['hostname'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ipblock',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipblock',
            name='instance_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
